name: JobBot (LinkedIn+InfoJobs+Indeed)

on:
  # Ejecuta cada día (UTC). Ajusta hora según quieras.
  schedule:
    - cron: "0 5 * * *"    # 05:00 UTC → 07:00 Madrid (verano), 06:00 UTC → 07:00 Madrid (invierno)
  # Permite lanzarlo a mano desde la pestaña Actions
  workflow_dispatch:

jobs:
  run-jobbot:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: pip-${{ runner.os }}-

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright + Chromium
        run: |
          python -m playwright install --with-deps chromium

      - name: Run JobBot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_USER_ID:  ${{ secrets.TELEGRAM_USER_ID }}
          KEYWORDS_INCLUDE:  ${{ vars.KEYWORDS_INCLUDE }}
          KEYWORDS_EXCLUDE:  ${{ vars.KEYWORDS_EXCLUDE }}
          LOCATIONS_INCLUDE: ${{ vars.LOCATIONS_INCLUDE }}
          REMOTE_ALLOWED:    ${{ vars.REMOTE_ALLOWED }}
          HOURS_BACK:        ${{ vars.HOURS_BACK }}
          RUN_MODE:          cron
        run: |
          python main.py
